server:
  port: 8080
  ssl:
    key-store: keystore.p12
    key-store-type: PKCS12
    key-store-password: 123456
    alias: spring
  http2:
    enabled: true

holoman:
  name: taylor
  howLong: 10

taylor:
  name: taylor
  age: ${random.int}
  fullName: ${taylor.name} Kang
